AllCops:
  TargetRubyVersion: 2.5.3

inherit_from: .rubocop_todo.yml

Metrics/AbcSize:
  Max: 32

Metrics/BlockLength:
  Max: 36

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false
